apiVersion: v1
kind: Secret
metadata:
  name: preprocessing-moma-secret
type: Opaque
stringData:
  preprocessing_moma.toml: |
    debug = true
    verbosity = 2

    sharedPath = "/tmp"

    [temporal]
    address = "temporal.enduro-sdps:7233"
    namespace = "default"
    taskQueue = "preprocessing"
    workflowName = "preprocessing"

    [worker]
    maxConcurrentSessions = 1
  .remove: |
    .DS_Store
