apiVersion: batch/v1
kind: Job
metadata:
  name: start-workflow
spec:
  backoffLimit: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: start-workflow
          image: temporalio/admin-tools:1.22.4
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal.enduro-sdps:7233
            - name: RELATIVE_PATH
              valueFrom:
                secretKeyRef:
                  name: start-workflow-secret
                  key: relative_path
            - name: WORKFLOW_INPUT
              value: '{"RelativePath": "$(RELATIVE_PATH)"}'
          command: [
              "sh",
              "-c",
              'temporal workflow start --task-queue=preprocessing --type=preprocessing --input="$WORKFLOW_INPUT"',
            ]
