run:
  deadline: 60s
  skip-dirs:
    - .github
    - hack

linters:
  enable:
    - gci
    - gofumpt
    - gosec
    - importas
    - misspell
    - unparam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  gci:
    no-inline-comments: true
    no-prefix-comments: false
    sections:
      - standard
      - default
      - prefix(github.com/artefactual-sdps/preprocessing-moma)
    section-separators:
      - newLine
  gofumpt:
    extra-rules: true
  importas:
    no-unaliased: true
    no-extra-aliases: false
    alias:
      - pkg: go.temporal.io/sdk/contrib/(\w+)
        alias: temporalsdk_contrib_$1
      - pkg: go.temporal.io/sdk/(\w+)
        alias: temporalsdk_$1
      - pkg: go.temporal.io/api/(\w+)
        alias: temporalapi_$1
  gosec:
    exclude-generated: false
    severity: low
    confidence: low
    excludes:
      - G601 # Implicit memory aliasing of items (only for Go 1.21 or lower)
