apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  labels:
    app: temporal-ui
spec:
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      serviceAccountName: sdps
      containers:
        - name: temporal-ui
          image: temporalio/ui:2.22.0
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal.enduro-sdps:7233
            - name: TEMPORAL_UI_PORT
              value: "8080"
            - name: TEMPORAL_CORS_ORIGINS
              value: http://localhost:7440
          ports:
            - containerPort: 8080
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  labels:
    app: temporal-ui
spec:
  selector:
    app: temporal-ui
  ports:
    - port: 8080
